---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

generators:
- ./secret-generator.yaml

namespace: "dh-dev-trino"

patchesJson6902:
  - patch: |
      - op: replace
        path: /data/s3_credentials_secret
        value: dev-aws-secret
    target:
      kind: ConfigMap
      name: trino-config
      version: v1
  - patch: |
      - op: replace
        path: /data/s3_endpoint_url
        value: https://s3.upshift.redhat.com/
    target:
      kind: ConfigMap
      name: trino-config
      version: v1
  - patch: |
      - op: replace
        path: /data/trino_environment
        value: development
    target:
      kind: ConfigMap
      name: trino-config
      version: v1
